language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

before_deploy:
  - cd $(bash before_deploy.sh)
  - pwd

deploy:
  - provider: pypi
    user:
      secure: "sGR39eR6z6/GGkvkV8vhiCWMOF6GqUf3yCOHCwZPm+aHP5CSWRr2xtwF45JnJ88uFi8kGPElZUFrCYghw2rkeLKCSqQ/4NNCXpwHy+QMSVSmLnB4UBeclMgj3LSt8zdMj5m1LOkBjtZHhTVNMdqwL1AUnzOcg2LD8y5GKNa1T000RcpmfrgcSlVxTwrr2aeGnUolQVfQLwy+iIC70VdRhOkdNdxg49WGMkqR03WOZq2VrJH4qaVxBVVE8aFEj1FED6tYGmhs14+zmlgH8/4yAxTY+2WErte6LJVjZVMqnSC7GGN8dWqBPB/mlxcmy3e6Yb5bjp71lVf2VklKi5I1hgHSsR7CSqJ84uq58RUseoN6yJkF6c71cB+6dnjEsVPyzqnoU2pQJ9Tk4FGC4FUNHIT7tf3SilknJCk1wqpyau6c9Z3VYoCJq/QAqspuoqgzRJhTlgdoG6JerNdBvAY4mCjKWjo0y5KBhD0750vqjODrMoDtOYgOHRMOdgtZR5sNzz9j7sCcBHL5TMHJ4kqqFElFCzdjYLC3SEJNCxmft24zYOmFQD5pIuKsnuu6gTyMfJRpABlp8W2uRjvWqlR3aX/YFMdwBiS4MK8HYkGTHnBpgyAGEsNjHE+TxmEDcvZWcYOBt6g6obYm+gbVjetI6/ynxSoLEJlS2vL4j+ViyT4="
    password:
      secure: "weCWwJCULa5ozSthgZ1D9Y7I/RUu74i28Q8LQotdjCkIXPm5QBts8UYmqhK04Rrewz/jyDjaK44dXNBrodQJN9LrMjfLVDWSY1pXMRUDdSvm/RuC53v4rnUrJT3aCmYKQ14CRcpOOw++aFkB2G3gbZZu3s3MlnGeIAF54YaXTnghkqkeEPXnAeMpqg+goYP/uq04b8eVsII4ka8GDMjAeJpA0/OZheYJyhrTlZNeRf1jvYpgB8B0A6dRzRBfhJD8VHRUhs9pOgbq7M8InnnMNOE5x2W5sSLRycBejjZ8pGDR71s/VFqhYZsO5rznCM6DbcDC1spuBw1bqb+scz8CZxHLWBGmXGA3WibnyflGqvrAA709iyJIGFfTLx1exX8q3lNlDd+fx5m0srUuUxvh8Ea+UH8/Bvb2Nn/Ui951bRBs9yVs5gsfkmbwjkGuc2D9DfRbMt6Wn7dFOL8jcuVeMcHIHiGVFUIo2Xl/6NHvKNu2pSrZLo7oweLBsPwnrhv/D1QOsEeCs7m5BmAaH+fw75dKoIjCH9KkqIqzmdkE1xnYKutrSJGFVSbTFjCbcvvHus4pUf9Vsnr/12QUTn8EAI/7pNCebJlLfaHpwgqeOJ62ZtOnau0rfecvh416T0200xSlHukzNArtE4QHWDzwGj29wgC68WDRAanfCyrdH/k="
    server: https://upload.pypi.org/legacy/
    skip_existing: true
    on:
      tags: true
      all_branches: true
      python: 3.4
