language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

before_deploy:
  - bash before_deploy.sh

deploy:
  provider: pypi
  user: TWINE_USERNAME
  password: TWINE_PASSWORD
  server: DEV_PYPI
  on:
    tags: true
    all_branches: true
    python: 3.4
