language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install twine

jobs:
  include:
    - stage: test
      script:
        - python main/main/test_main.py
        - python secondary/secondary/test_secondary.py
    - stage: deploy-main
      if: tag =~ /^(main)
      python: 3.4
      provider: pypi
      user: TWINE_USERNAME
      password: TWINE_PASSWORD
      server: DEV_PYPI
      on:
        all_branches: true
    - stage: deploy-secondary
      if: tag =~ /^(secondary)
      python: 3.4
      provider: pypi
      user: TWINE_USERNAME
      password: TWINE_PASSWORD
      server: DEV_PYPI
      on:
        all_branches: true
