language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine


jobs:
  include:
    - stage: test
      script:
        - python main/main/test_main.py
        - python secondary/secondary/test_secondary.py
    - stage: deploy-to-pypi-main
      if: tag =~ main
      script: ls main/
