language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py


after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)\n"
  - if (branch =~ master) fi
      # python main/setup.py sdist
      ls main/
      twine upload --repository-url DEV_PYPI dist/*

    if tag =~ secondary fi
      echo "this is tagged secondary!"
