language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install twine

script:
  - python main/test_main.py
  - python secondary/test_secondary.py

deploy:
  if: tag =~ main AND branch = master
  script:
    - cd tdvt && python setup.py sdist
    - twine upload --repository-url DEV_PYPI main/dist/*
    # - twine upload --repository-url PRD_PYPI tdvt/dist/*

  if: tag =~ secondary AND branch = master
    script:
    - cd secondary && python setup.py sdist
    - twine upload --repository-url DEV_PYPI secondary/dist/*
    # - twine upload --repository-url PRD_PYPI secondary/dist/*
