language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py


after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"

deploy:
    if tag =~ main AND branch = master fi
      echo "this is tagged master@!"

    if tag =~ secondary AND branch = master fi
      echo "this is tagged secondary!"
