language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine

jobs:
  include:
    - stage: test
      script:
        - python main/main/test_main.py
        - python secondary/secondary/test_secondary.py
    - stage: deploy-main-to-pypy
      if: tag =~ main
        script:
          - ls main/
    - stage: deploy-secondary-to-pypy
      if: tag =~ secondary
        script:
          - ls secondary/
