language: python

python:
  - "3.4"

stages:
  - name: test
    script: python main/main/test_main.py
    script: python secondary/secondary/test_secondary.py
  - name: deploy-main
    if: (tag =~ /^(main))
    provider: pypi
    user: TWINE_USERNAME
    password: TWINE_PASSWORD
    server: DEV_PYPI
    on:
      all_branches: true
  - name: deploy-secondary
    if: tag =~ /^(secondary)
    provider: pypi
    user: TWINE_USERNAME
    password: TWINE_PASSWORD
    server: DEV_PYPI
    on:
      all_branches: true
