language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install twine

jobs:
  include:
    - stage: test
      script:
        - python main/main/test_main.py
        - python secondary/secondary/test_secondary.py
    - stage: deploy
      python: 3.4
      provider: script
      script: bash deploy.sh DEV_PYPI
      on:
        all_branches: true
