language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

after_success:
  - if: main IN "$TRAVIS_TAG"
    ls main/
  - if: secondary IN "$TRAVIS_TAG"
    ls secondary/
  - if: tag
    echo "$tag"
  - if: TRAVIS_TAG
    echo "$TRAVIS_TAG"
