language: python

python:
  - "3.4"
  - "3.5"

install:
  - pip install twine

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

after_success:
  echo "$TRAVIS_TAG"
  - if "$TRAVIS_TAG" =~ /^(main)
    ls main/
