stages:
  - name: test
    python:
    - "3.4"
    - "3.5"
    - "3.6"
    script:
      - python main/main/test_main.py
      - python secondary/secondary/test_secondary.py
  - name: deploy
      if: tag =~ /^(main)
      provider: pypi
      user: TWINE_USERNAME
      password: TWINE_PASSWORD
      server: DEV_PYPI
      on:
        all_branches: true
  - name: deploy
      if: tag =~ /^(secondary)
      provider: pypi
      user: TWINE_USERNAME
      password: TWINE_PASSWORD
      server: DEV_PYPI
      on:
        all_branches: true
