language: python

python:
  - "3.4"

install:
  - pip install twine

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

on_success:
  - script: bash deploy.sh
