language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python main/main/test_main.py
  - python secondary/secondary/test_secondary.py

before_deploy:
  - cd $(bash before_deploy.sh)
  - pwd

deploy:
  - provider: pypi
    server: $DEV_PYPI
    skip_existing: true
    on:
      tags: true
      all_branches: true
      python: 3.4
